// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include "frc/commands/Subsystem.h"
#include "rev/CANSparkMax.h"
#include "frc/SpeedControllerGroup.h"
#include "frc/drive/DifferentialDrive.h"
#include "adi/ADIS16448_IMU.h"
#include "ctre/Phoenix.h"
#include "frc/DoubleSolenoid.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveTrain: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	std::shared_ptr<rev::CANSparkMax> leftA;
	std::shared_ptr<rev::CANSparkMax> leftB;
	std::shared_ptr<rev::CANSparkMax> rightA;
	std::shared_ptr<rev::CANSparkMax> rightB;
	std::shared_ptr<frc::SpeedControllerGroup> groupLeft;
	std::shared_ptr<frc::SpeedControllerGroup> groupRight;
	std::shared_ptr<frc::DifferentialDrive> diffDrive;
	std::shared_ptr<frc::DoubleSolenoid> shiftSolenoid;
	std::shared_ptr<frc::ADIS16448_IMU> imu;
	//std::shared_ptr<WPI_TalonFX> GyroMotor;
	DriveTrain();
	void InitDefaultCommand() override;
	void Periodic() override;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
const double CircumWheel = 5.000 * 3.141592; //diameter is 5 inches
const double LowGearRatio = 1 / 13.44;
const double HighGearRatio = 1 / 5.39;
double GetLinearDistance();
bool isReversed = false;


};

