// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#pragma once

#include "frc/Joystick.h"
#include "frc/buttons/JoystickButton.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

















std::shared_ptr<frc::Joystick> coPilot;
std::shared_ptr<frc::JoystickButton> rightStickIn2;
std::shared_ptr<frc::JoystickButton> leftStickIn2;
std::shared_ptr<frc::JoystickButton> rightButton2;
std::shared_ptr<frc::JoystickButton> leftBumper2;
std::shared_ptr<frc::JoystickButton> x2;
std::shared_ptr<frc::JoystickButton> b2;
std::shared_ptr<frc::JoystickButton> y2;
std::shared_ptr<frc::JoystickButton> a2;
std::shared_ptr<frc::Joystick> driver;
std::shared_ptr<frc::JoystickButton> rightStickIn;
std::shared_ptr<frc::JoystickButton> leftstickIn;
std::shared_ptr<frc::JoystickButton> leftBumper;
std::shared_ptr<frc::JoystickButton> x;
std::shared_ptr<frc::JoystickButton> b;
std::shared_ptr<frc::JoystickButton> rightBumper;
std::shared_ptr<frc::JoystickButton> y;
std::shared_ptr<frc::JoystickButton> a;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

std::shared_ptr<frc::Joystick> getDriver();
std::shared_ptr<frc::Joystick> getCoPilot();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

static const int LEFT_Y_AXIS = 1;
static const int RIGHT_Y_AXIS = 5;

};

