// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Commands/ShooterDefault.h"
#include "frc/smartdashboard/SmartDashboard.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ShooterDefault::ShooterDefault(): frc::Command() {
    // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ShooterDefault::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void ShooterDefault::Execute() {
    double targetVelPer100ms = Robot::shooter->rpmToDeltaPer100ms(Robot::shooter->targetSpeed);
    frc::SmartDashboard::PutNumber("targetSpeed", Robot::shooter->targetSpeed);
    frc::SmartDashboard::PutNumber("targetVel100ms", targetVelPer100ms);
    frc::SmartDashboard::PutNumber("shooterLeft encoder", Robot::shooter->shooterLeft->GetSelectedSensorVelocity());
    frc::SmartDashboard::PutNumber("shooterRight encoder", Robot::shooter->shooterRight->GetSelectedSensorVelocity());
    frc::SmartDashboard::PutBoolean("isShoot", Robot::shooter->isShoot);

    if (Robot::shooter->isShoot){
        //look at falcon documetation for closed loop
        Robot::shooter->shooterLeft->Set(ControlMode::Velocity, targetVelPer100ms);
    }
    else{
        Robot::shooter->shooterLeft->Set(ControlMode::PercentOutput, 0.0);
    }
    
   //Robot::shooter->shooterLeft->Set(Robot::oi->getDriver()->GetRawAxis(1)); // axis 1 for left analog y-axis
   //Robot::shooter->shooterLeft->Set(ControlMode::PercentOutput, Robot::oi->getDriver()->GetRawAxis(1));

}

// Make this return true when this Command no longer needs to run execute()
bool ShooterDefault::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ShooterDefault::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterDefault::Interrupted() {

}
