// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "Commands/TimedElevator.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TimedElevator::TimedElevator(double timeout) : frc::TimedCommand(timeout) {
    // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
TimedElevator::TimedElevator(double timeout, double speed) : frc::TimedCommand(timeout) {
    ElevateSpeed = speed;
    Requires(Robot::elevator.get());
}
// Called just before this Command runs the first time
void TimedElevator::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void TimedElevator::Execute() {
    Robot::elevator->elevateMotor->Set(ElevateSpeed);

}

// Called once after command times out
void TimedElevator::End() {
    Robot::elevator->elevateMotor->Set(0.0);

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TimedElevator::Interrupted() {

}
